services:
  - type: web
    name: safetap
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_XANO_URL
        sync: false
      - key: CI
        value: "false"
